apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    field.cattle.io/publicEndpoints: '[{"addresses":["146.190.14.75"],"port":443,"protocol":"HTTPS","serviceName":"strapi:strapi-cms","ingressName":"strapi:strapi-ingress","hostname":"cms.rurich.dev","path":"/","allNodes":false}]'
  creationTimestamp: "2022-12-31T20:12:29Z"
  generation: 13
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-strapi-strapi-cms
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
            f:spec:
              f:affinity: {}
              f:containers:
                k:{"name":"strapi"}:
                  .: {}
                  f:envFrom: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":1337,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"registry-always-sunny"}: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: rancher
      operation: Update
      time: "2022-12-31T20:20:36Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2023-02-03T04:53:49Z"
  name: strapi-cms
  namespace: strapi
  resourceVersion: "28711876"
  uid: c11c02e7-b6e6-494e-a194-eb4126c50e01
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-strapi-strapi-cms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2023-01-13T04:34:06Z"
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-strapi-strapi-cms
    spec:
      affinity: {}
      containers:
        - envFrom:
            - secretRef:
                name: platform
                optional: false
          image: registry.digitalocean.com/always-sunny/strapi
          imagePullPolicy: Always
          name: strapi
          ports:
            - containerPort: 1337
              name: 1337tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-always-sunny
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: "2022-12-31T20:12:29Z"
      lastUpdateTime: "2023-01-13T04:34:38Z"
      message: ReplicaSet "strapi-cms-85fb8d4c9d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-02-03T04:53:49Z"
      lastUpdateTime: "2023-02-03T04:53:49Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 13
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["strapi/strapi-cms"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-12-31T20:12:29Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c11c02e7-b6e6-494e-a194-eb4126c50e01"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":1337,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: "2022-12-31T20:12:29Z"
  name: strapi-cms
  namespace: strapi
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: strapi-cms
      uid: c11c02e7-b6e6-494e-a194-eb4126c50e01
  resourceVersion: "5043891"
  uid: 2f54dcb2-8513-4af8-803f-2e8600468ee7
spec:
  clusterIP: 10.245.196.79
  clusterIPs:
    - 10.245.196.79
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 1337tcp
      port: 1337
      protocol: TCP
      targetPort: 1337
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-strapi-strapi-cms
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
