on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deps
        run: yarn
      
      - name: Run Tests
        with: 
          env: ${{secrets.JWT_TOKEN}}
        run: yarn test
        
