on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JWT_SECRET }}

      - name: Install Deps
        run: yarn
      
      - name: Run Tests
        run: yarn test
        
